---
title: "Introducción"
author: "Maximiliano Norbu"
date: "09-11-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introducción

 Tanto el peso como la estatura de un bebé al nacer son factores importantes que indican si este está sano o no. Lo habitual para los bebés es pesar alrededor de 3.5 kg y medir alrededor de 50 cm al nacer (aunque los hombres suelen pesar y medir un poco más). Si el peso y/o altura del recién nacido se alejaran demasiado de las medidas standard, este puede ser más propenso a presentar problemas de salud. Es conocido que tanto características del padre, como de la madre pueden afectar a estas medidas. También es lógico pensar que las semanas de gestación que haya tenido el feto pueden tener efecto en el desarrollo que este presente al nacer. Sin embargo, también se dice mucho que ciertas acciones realizadas por la madre durante el embarazo pueden afectar la salud del infante. Estas pueden ir desde pintar la casa o estar mucho tiempo parada, hasta consumir drogas; que pueden ser legales como el café, el tabaco o el alcohol, o ilegales, como la marihuana o la heroína. Esto es importante, pues estas son actividades que se pueden evitar, con el objetivo de prevenir riesgos. 

 Ahora bien, estas son aseveraciones sin mucha profundidad. Al escuchar una frase como “no debes tomar alcohol durante el embarazo”, muchas cosas no quedan claras. Por ejemplo, si tomé un sorbo, ¿ya es suficiente para afectar al bebé?, ¿hay diferencia entre tomar un vaso de licor y, por ejemplo, tres vasos? No obstante, lo que más me llamó la atención fue el tema del tabaco, esto pues, es de las pocas sustancias que puede entrar a tu cuerpo sin que seas tú quien la está consumiendo (fumador pasivo).

 Por esto decidí investigar para responder la pregunta, ¿Cuánto afecta a la estatura y peso del recién nacido que el padre o la madre fumen durante el embarazo? Más específicamente, me gustaría encontrar una relación lineal entre la estatura del recién nacido y la cantidad de cigarrillos consumida (por la madre y luego por el padre), y después, una relación entre el peso y los cigarrillos. Me gustaría saber la diferencia que hay si alguno de los padres fumador y si ninguno fuma; además de la diferencia entre padre fumador y madre fumadora. Finalmente, me interesa la diferencia entre padres que fuman poco y padres que fuman mucho.
 
 Mi informe se organizará se la siguiente manera: primero se discutirá respecto a cuanto nos dice la estatura y peso del bebé respecto al riesgo de enfermedades. Esto pues, mi estudio busca ver cambios en el peligro de problemas a la salud del bebé respecto del uso del cigarrillo; sin embargo, las medidas utilizadas son medidas físicas (peso y altura) pues son más fáciles y objetivas de medir. Segundo, hablaré de las características de mi base de datos, de qué modificaciones le haré y como se obtuvo. Luego, para el fuerte del estudio, haré las distintas regresiones lineales y mostraré los modelos que obtenga a partir de estas, incluyendo tanto las fórmulas como algunos gráficos para facilitar la visualización de los resultados. Finalmente, concluiré a partir de lo que logre observar de los distintos modelos lineales.
 

## links:

[Link 1](https://www.urmc.rochester.edu/encyclopedia/content.aspx?contenttypeid=90&contentid=P02673)

[Link 2](https://www.uofmhealth.org/health-library/te6295#:~:text=The%20average%20birth%20weight%20for,usually%20lighter%20than%20later%20siblings.)

[Link 3](https://www.cdc.gov/reproductivehealth/maternalinfanthealth/substance-abuse/substance-abuse-during-pregnancy.htm#:~:text=Smoking%20during%20pregnancy%20increases%20the,infant%20death%20syndrome%20(SIDS).)

[Link 4](https://www.healthline.com/health/pregnancy/things-not-to-do-while-pregnant)

[Link 5](https://en.wikipedia.org/wiki/Passive_smoking)
